DATASET_ROOT: 'shapenet_plain'
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/index/shapenet_plain_chair_mini_test.json']
MODES: ['test']
MODEL: 'pix2surf_sv_render'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 1
LR: 0.0

LOG_DIR: 'render-pix2surf-sv-chair-plain'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls','obj']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False

RESUME: False
MODEL_INIT_PATH: ['resource/weight/eccv_pix2surf_sv_chair_plain_epoch_30.model']

BACKUP_FILES: ['core/net_bank/pix2surf_cnn.py',
               'core/net_bank/mlp.py',
               'core/net_bank/loss.py',
               'core/models/pix2surf_sv.py',
               'core/models/utils/model_utils.py',
               'core/models/utils/render_utils.py']

RENDER_MASK_TH: 0.03
RENDER_IMAGE_MASK_NK: 2