DATASET_ROOT: 'shapenet_coco'
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/index/shapenet_coco_chair_train.json',
                'resource/index/shapenet_coco_chair_test.json']
MODES: ['test']
MODEL: 'pix2surf_sv_mveval'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 1
LR: 0.0

LOG_DIR: 'eval-pix2surf-sv-chair-coco'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 10
VIS_ONE_PER_BATCH: True

RESUME: False
MODEL_INIT_PATH: ['resource/weight/eccv_pix2surf_sv_chair_coco_epoch_30.model']

BACKUP_FILES: ['core/net_bank/pix2surf_cnn.py',
               'core/net_bank/mlp.py',
               'core/net_bank/loss.py',
               'core/evaluation.py',
               'core/models/pix2surf_sv.py',
               'core/models/utils/model_utils.py',
               'core/models/utils/render_utils.py']