DATASET_ROOT: 'shapenet_coco'
DATASET: 'neurips_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/index/shapenet_coco_plane_train.json',
                'resource/index/shapenet_coco_plane_vali.json',
                'resource/index/shapenet_coco_plane_test.json']
MODES: ['train','vali']
MODEL: 'pix2surf_sv'

GPU: [0,1]
BATCHSIZE: 16
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 30
LR: 3e-5

LOG_DIR: 'pix2surf-sv-plane-coco'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 5
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 50
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 100

RESUME: False
MODEL_INIT_PATH: ['log/xnocs-init-sv-plane-coco/model/epoch_30.model']

BACKUP_FILES: ['core/net_bank/pix2surf_cnn.py',
               'core/net_bank/mlp.py',
               'core/net_bank/loss.py',
               'core/models/utils/model_utils.py',
               'core/models/utils/render_utils.py']